services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 50M
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=false
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_USERSPACE=false
    network_mode: host
    volumes:
      - ./data/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    security_opt:
      - no-new-privileges=true
    cap_add:
      - net_admin
      - sys_module
      - net_raw
      - chown
      - dac_override
      - fowner
    cap_drop:
      - all
