services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    networks:
      adguard:
        ipv4_address: 192.168.0.10
      traefik:
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguardhome.rule=Host(`${ADGUARDHOME_HOSTNAME}`)
      - traefik.http.routers.adguardhome.entrypoints=websecure
      - traefik.http.routers.adguardhome.tls=true
      - traefik.http.routers.adguardhome.tls.certresolver=cloudflare
      - traefik.http.services.adguardhome.loadbalancer.server.port=80
      - docker-volume-backup.stop-during-backup=true

networks:
  adguard:
    external: true
  traefik:
    external: true
