services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "443:443/udp"
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguardhome.rule=Host(`${ADGUARDHOME_HOSTNAME}`)
      - traefik.http.routers.adguardhome.entrypoints=websecure
      - traefik.http.routers.adguardhome.tls=true
      - traefik.http.routers.adguardhome.tls.certresolver=cloudflare
      - traefik.http.services.adguardhome.loadbalancer.server.port=80
      - docker-volume-backup.stop-during-backup=true

networks:
  traefik:
    external: true
